---
- name: Create the certs directory
  ansible.builtin.file:
    path: "{{ gitea_work_path }}/certs"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: '0750'
    state: directory

- name: Generate the self-signed certs for Gitea
  ansible.builtin.command: >
    gitea cert
    --host {{ gitea_domain }},{{ gitea_ssh_domain }}
    --out {{ gitea_work_path }}/certs/cert.pem
    --keyout {{ gitea_work_path }}/certs/key.pem
  become: true
  become_user: "{{ gitea_user }}"
  args:
    creates: "{{ gitea_work_path }}/certs/cert.pem"
